import { INITIAL_CATEGORIES, INITIAL_LOCATIONS } from '../config/constants';
import { ActivityLog, Admin, Complaint } from '../types';

export const INITIAL_ADMINS: Admin[] = [
  {
    admin_id: 'ADM-001',
    name: 'Chief Proctor',
    email: 'chiefproctor@college.edu',
    role: 'Chief Proctor',
    status: 'Active',
    passkey: 'proctor2026',
    created_at: '2026-01-10T09:00:00.000Z',
    last_login: '2026-08-18T08:15:00.000Z',
  },
  {
    admin_id: 'ADM-002',
    name: 'Admin Office',
    email: 'admin@college.edu',
    role: 'Admin',
    status: 'Active',
    passkey: 'proctor2026',
    created_at: '2026-01-15T10:30:00.000Z',
    last_login: '2026-08-17T16:45:00.000Z',
  },
  {
    admin_id: 'ADM-003',
    name: 'Campus Security Staff',
    email: 'security.staff@college.edu',
    role: 'Staff',
    status: 'Active',
    passkey: 'proctor2026',
    created_at: '2026-02-01T11:00:00.000Z',
    last_login: '2026-08-18T07:30:00.000Z',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    complaint_id: 'CQB-20260818-A7F2',
    submitted_at: '2026-08-18T09:15:00.000Z',
    updated_at: '2026-08-18T09:15:00.000Z',
    is_anonymous: true,
    category: 'Electricity',
    title: 'Ceiling fans not functioning in Academic Block A (Room 302)',
    description: 'During afternoon lectures, the two middle ceiling fans make a grinding noise and do not spin. The classroom becomes extremely hot and students cannot concentrate.',
    location: 'Academic Block A',
    priority: 'Medium',
    status: 'New',
  },
  {
    complaint_id: 'CQB-20260817-C3D9',
    submitted_at: '2026-08-17T14:30:00.000Z',
    updated_at: '2026-08-18T10:00:00.000Z',
    is_anonymous: false,
    student_name: 'Rahul Sharma',
    student_id: '2023-CS-084',
    department: 'Computer Science & Engineering',
    semester: 'Semester 5',
    contact: '+91 98765 43210',
    category: 'IT/Internet',
    title: 'High-speed Wi-Fi disconnected in Computer Lab 2',
    description: 'The access point in Lab 2 has been offline for two days, blocking practical programming submissions on the portal.',
    location: 'Computer Lab 1 & 2',
    priority: 'High',
    status: 'In Progress',
    admin_remarks: 'Dispatched campus IT technician to inspect network switch and reboot gateway.',
    assigned_to: 'Prof. Margaret Hayes',
  },
  {
    complaint_id: 'CQB-20260816-B8E1',
    submitted_at: '2026-08-16T11:20:00.000Z',
    updated_at: '2026-08-17T15:00:00.000Z',
    is_anonymous: true,
    category: 'Cleanliness',
    title: 'Water cooler drainage overflow near Central Library entrance',
    description: 'The drainage tray under the 2nd floor water cooler is overflowing onto the corridor floor, creating a slip hazard.',
    location: 'Central Library',
    priority: 'Medium',
    status: 'Resolved',
    admin_remarks: 'Housekeeping team dispatched and drainage pipe cleared.',
    resolution: 'The drainage pipe was unblocked and sanitized by maintenance staff on Aug 17. Floor dry and safe.',
    resolved_at: '2026-08-17T15:00:00.000Z',
    assigned_to: 'Dr. Arthur Vance',
  },
  {
    complaint_id: 'CQB-20260815-E4A6',
    submitted_at: '2026-08-15T18:45:00.000Z',
    updated_at: '2026-08-16T09:30:00.000Z',
    is_anonymous: true,
    category: 'Security',
    title: 'Street light malfunction near Student Parking Area Gate 3',
    description: 'The high-mast floodlight near the evening exit is flickering violently, leaving the vehicle walkway pitch dark after 7:30 PM.',
    location: 'Student Parking Area',
    priority: 'Critical',
    status: 'Assigned',
    admin_remarks: 'Forwarded to Estate Maintenance electrical contractor for urgent evening replacement.',
    assigned_to: 'Officer Rajesh Kumar',
  },
  {
    complaint_id: 'CQB-20260814-F9D2',
    submitted_at: '2026-08-14T10:05:00.000Z',
    updated_at: '2026-08-15T11:15:00.000Z',
    is_anonymous: false,
    student_name: 'Ananya Verma',
    student_id: '2024-EC-019',
    department: 'Electronics & Communication',
    semester: 'Semester 3',
    contact: '+91 91234 56789',
    category: 'Hostel',
    title: 'Hot water geyser tripping MCB in Block B 2nd floor bathroom',
    description: 'Whenever the geyser is switched on in the morning, the floor electrical circuit trips completely.',
    location: 'Hostel Boys / Girls',
    priority: 'High',
    status: 'Under Review',
    admin_remarks: 'Hostel warden notified. Awaiting electrical inspection report.',
    assigned_to: 'Prof. Margaret Hayes',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    log_id: 'LOG-001',
    timestamp: '2026-08-18T10:00:00.000Z',
    admin_id: 'ADM-002',
    admin_name: 'Prof. Margaret Hayes',
    complaint_id: 'CQB-20260817-C3D9',
    action: 'STATUS_UPDATE',
    old_value: 'Under Review',
    new_value: 'In Progress',
    remarks: 'Assigned technician to reset lab switch.',
  },
  {
    log_id: 'LOG-002',
    timestamp: '2026-08-17T15:00:00.000Z',
    admin_id: 'ADM-001',
    admin_name: 'Dr. Arthur Vance',
    complaint_id: 'CQB-20260816-B8E1',
    action: 'STATUS_RESOLVED',
    old_value: 'In Progress',
    new_value: 'Resolved',
    remarks: 'Drainage pipe unblocked and verified by proctor patrol.',
  },
  {
    log_id: 'LOG-003',
    timestamp: '2026-08-16T09:30:00.000Z',
    admin_id: 'ADM-001',
    admin_name: 'Dr. Arthur Vance',
    complaint_id: 'CQB-20260815-E4A6',
    action: 'PRIORITY_UPDATE',
    old_value: 'High',
    new_value: 'Critical',
    remarks: 'Escalated due to nighttime security hazard.',
  },
];

export { INITIAL_CATEGORIES, INITIAL_LOCATIONS };
